### ISSUE TITLE
how do we use model view controllers?

### ISSUE THREAD

**Issue by lastlink** [melihercan/Xamarinme#1]

**Comment by melihercan** [comment]
I really don't understand the relevance and the question.

**Comment by lastlink** [comment]
None of your examples show using the standard api controllers from .net.

**Comment by melihercan** [comment]
> None of your examples show using the standard api controllers from .net.

standard api controllers? 
Do you mean WEB API controllers? This library is for Xamarin apps not for WEB.

**Comment by lastlink** [comment]
But isn't the main idea to embed the .NET Core Hosting into Xamarin?

**Comment by lastlink** [comment]
nvm I figured it out, thanks for your examples so far.
